import React, { useState } from 'react';
import { 
  AlertCircle, 
  AlertTriangle, 
  Info, 
  CheckCircle2, 
  Settings, 
  Clock, 
  User, 
  ArrowRight, 
  FileText, 
  ShieldAlert, 
  TrendingDown, 
  HelpCircle,
  X,
  Check,
  RotateCcw,
  Sliders,
  DollarSign,
  Package,
  Layers,
  Filter,
  CheckSquare,
  MessageSquare,
  Lock,
  Download,
  ShieldCheck,
  Send,
  Radio,
  Users,
  Megaphone,
  Plus
} from 'lucide-react';
import { can } from '../../utils/permissions';

export default function AttentionCenterView({ onShowToast, currentRole = 'MANAGER', onNavigate }) {
  const [activeFilter, setActiveFilter] = useState('ALL'); // 'ALL' | 'MESSAGES' | 'ALERTS' | 'APPROVALS' | 'ANNOUNCEMENTS' | 'HISTORY_BOARD'
  const [selectedAlertForExplanation, setSelectedAlertForExplanation] = useState(null);
  
  // Custom Modals State
  const [showComposer, setShowComposer] = useState(false);
  const [composerScope, setComposerScope] = useState('INDIVIDUAL'); // 'INDIVIDUAL' | 'TEAM' | 'BROADCAST'
  const [composerRecipient, setComposerRecipient] = useState('EMP-00014 (Sales Staff)');
  const [composerTeam, setComposerTeam] = useState('Warehouse Team');
  const [composerSubject, setComposerSubject] = useState('');
  const [composerBody, setComposerBody] = useState('');
  const [composerPriority, setComposerPriority] = useState('NORMAL');
  const [composerRelatedRecord, setComposerRelatedRecord] = useState('PO-2026-00431');
  const [composerRequireAck, setComposerRequireAck] = useState(true);

  // Decision Modal
  const [decisionModalEntity, setDecisionModalEntity] = useState(null);
  const [decisionNote, setDecisionNote] = useState('');
  
  // Staff Note Modal
  const [staffNoteModalEntity, setStaffNoteModalEntity] = useState(null);
  const [staffObservationNote, setStaffObservationNote] = useState('');

  // Sensitive Export Modal
  const [exportConsentModal, setExportConsentModal] = useState(null);
  const [exportReason, setExportReason] = useState('');

  const isManager = can(currentRole, 'attention.decide');
  const canBroadcast = can(currentRole, 'broadcast.send');

  // Operational Communication & System Event Stream
  const [items, setItems] = useState([
    {
      id: 1,
      code: 'APPROVAL-REF-00042',
      type: 'APPROVAL', // APPROVAL | ALERT | MESSAGE | ANNOUNCEMENT
      scope: 'SYSTEM_EVENT',
      importance: 'ACTION_REQUIRED',
      title: 'Refund Approval Required: #REF-00042',
      summary: 'Customer ABC Traders requested $340.00 refund on receipt SAL-00182.',
      sender: 'SYSTEM_ENGINE (Triggered by EMP-00014)',
      timestamp: '2026-08-26T01:45:00Z',
      lifecycle: 'ACTION_REQUIRED',
      relatedRecord: 'REF-00042',
      details: {
        customer: 'ABC Traders',
        amount: 340.00,
        receipt_id: 'SAL-00182',
        reason: 'Duplicate Transaction'
      },
      whyExplanation: {
        trigger: 'Refund Amount Exceeds Staff Authorization Threshold ($100.00)',
        formula: 'Requested Refund ($340.00) > Staff Limit ($100.00) → Manager Approval Required',
        auditRef: 'AUD-REF-2026-0042'
      },
      staffNotes: [],
      historyTrail: [{ time: '01:45 UTC', event: 'Approval request generated by POS' }]
    },
    {
      id: 2,
      code: 'ALERT-CAT6',
      type: 'ALERT',
      scope: 'SYSTEM_EVENT',
      importance: 'IMPORTANT',
      title: 'Critical Inventory Alert: CAT6 Cable Roll 300m',
      summary: 'CAT6 Cable has fallen below safety reorder level (Current: 3, Minimum: 10).',
      sender: 'SYSTEM_ENGINE',
      timestamp: '2026-08-26T01:30:00Z',
      lifecycle: 'IMPORTANT',
      relatedRecord: 'SKU-CAT6-300M',
      details: { currentStock: 3, minBuffer: 10, unitPrice: 45.00 },
      whyExplanation: {
        trigger: 'Reorder Buffer Breach',
        formula: 'Available Stock (3) < Safety Threshold (10) → Reorder PO Recommended',
        auditRef: 'AUD-BUF-9402'
      },
      staffNotes: [],
      historyTrail: [{ time: '01:30 UTC', event: 'Reorder alert triggered by Stock Monitor' }]
    },
    {
      id: 3,
      code: 'MSG-PO-00431',
      type: 'MESSAGE',
      scope: 'INDIVIDUAL',
      importance: 'IMPORTANT',
      title: 'Direct Message: PO-00431 Receiving Discrepancy',
      summary: 'Please verify the quantity received against GRN #882 for PO-00431.',
      sender: 'Sarah Jenkins (Warehouse Manager)',
      recipient: 'EMP-00022 (Receiving Operator)',
      timestamp: '2026-08-26T01:10:00Z',
      lifecycle: 'IMPORTANT',
      relatedRecord: 'PO-2026-00431',
      staffNotes: [{ author: 'EMP-00022', time: '01:15 UTC', note: 'Supplier driver confirmed 4 units backordered on delivery slip.' }],
      historyTrail: [{ time: '01:10 UTC', event: 'Direct operational message sent with PO-00431 reference' }]
    },
    {
      id: 4,
      code: 'ANNOUNCEMENT-2026-001',
      type: 'ANNOUNCEMENT',
      scope: 'BROADCAST',
      importance: 'IMPORTANT',
      title: 'System Maintenance & Nightly Stock Freeze',
      summary: 'Inventory system maintenance will occur tonight from 22:00–23:00. POS transactions must be synced before 22:00.',
      sender: 'Taa (App Admin)',
      audience: 'All Warehouse & Sales Staff',
      timestamp: '2026-08-26T00:30:00Z',
      lifecycle: 'INFORMATIONAL',
      requireAck: true,
      acknowledgements: {
        totalRequired: 8,
        confirmedCount: 6,
        confirmedUsers: ['John M.', 'Sarah J.', 'Michael T.', 'Peter K.', 'James L.', 'David R.'],
        pendingUsers: ['Brian S.', 'Thomas W.']
      },
      historyTrail: [{ time: '00:30 UTC', event: 'Org-wide broadcast issued by Administrator' }]
    }
  ]);

  // Handle Send New Message / Broadcast
  const handleSendMessage = () => {
    if (!composerSubject.trim() || !composerBody.trim()) {
      if (onShowToast) onShowToast('warning', 'Incomplete Message', 'Subject and Message body are required.');
      return;
    }

    const newItem = {
      id: Date.now(),
      code: `MSG-${Date.now().toString().slice(-4)}`,
      type: composerScope === 'BROADCAST' ? 'ANNOUNCEMENT' : 'MESSAGE',
      scope: composerScope,
      importance: composerPriority === 'URGENT' ? 'ACTION_REQUIRED' : 'IMPORTANT',
      title: composerSubject,
      summary: composerBody,
      sender: `${currentRole} User (Taa)`,
      recipient: composerScope === 'INDIVIDUAL' ? composerRecipient : composerScope === 'TEAM' ? composerTeam : 'All Staff',
      timestamp: new Date().toISOString(),
      lifecycle: 'IMPORTANT',
      relatedRecord: composerRelatedRecord || 'N/A',
      requireAck: composerRequireAck,
      acknowledgements: composerRequireAck ? {
        totalRequired: 8,
        confirmedCount: 1,
        confirmedUsers: [`${currentRole} User`],
        pendingUsers: ['Sarah J.', 'Michael T.', 'Peter K.', 'Brian S.', 'Thomas W.', 'David R.', 'James L.']
      } : null,
      staffNotes: [],
      historyTrail: [{ time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), event: `Message sent by ${currentRole}` }]
    };

    setItems(prev => [newItem, ...prev]);
    if (onShowToast) onShowToast('success', 'Message Transmitted', `Operational ${composerScope.toLowerCase()} message sent successfully.`);
    setShowComposer(false);
    setComposerSubject('');
    setComposerBody('');
  };

  // Handle Acknowledgement
  const handleAcknowledge = (item) => {
    setItems(prev => prev.map(i => {
      if (i.id === item.id && i.acknowledgements) {
        return {
          ...i,
          acknowledgements: {
            ...i.acknowledgements,
            confirmedCount: i.acknowledgements.confirmedCount + 1,
            confirmedUsers: [...i.acknowledgements.confirmedUsers, `${currentRole} User`]
          }
        };
      }
      return i;
    }));
    if (onShowToast) onShowToast('info', 'Acknowledgement Confirmed', `You acknowledged operational instruction #${item.code}.`);
  };

  // Handle Manager Decision
  const handleExecuteManagerDecision = () => {
    if (!decisionModalEntity || !decisionNote.trim()) {
      if (onShowToast) onShowToast('warning', 'Manager Note Required', 'Must attach mandatory decision note.');
      return;
    }

    const { item, decision } = decisionModalEntity;
    setItems(prev => prev.map(i => {
      if (i.id === item.id) {
        return {
          ...i,
          importance: 'RESOLVED',
          lifecycle: 'RESOLVED',
          title: `Resolved (${decision}): ${i.title}`,
          details: { ...i.details, managerDecision: decision, managerNote: decisionNote },
          historyTrail: [
            ...i.historyTrail,
            { time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), event: `Manager Decision (${decision}) executed. Note: ${decisionNote}` }
          ]
        };
      }
      return i;
    }));

    if (onShowToast) onShowToast('success', `Decision Executed (${decision})`, `Item #${item.code} resolved and logged.`);
    setDecisionModalEntity(null);
    setDecisionNote('');
  };

  // Handle Staff Note Attachment
  const handleAddStaffNote = () => {
    if (!staffNoteModalEntity || !staffObservationNote.trim()) return;
    setItems(prev => prev.map(i => {
      if (i.id === staffNoteModalEntity.id) {
        return {
          ...i,
          staffNotes: [
            ...i.staffNotes,
            { author: `${currentRole} User`, time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), note: staffObservationNote }
          ]
        };
      }
      return i;
    }));
    if (onShowToast) onShowToast('info', 'Observation Note Attached', `Note added to #${staffNoteModalEntity.code}.`);
    setStaffNoteModalEntity(null);
    setStaffObservationNote('');
  };

  // Filter Items
  const filteredItems = items.filter(i => {
    if (activeFilter === 'MESSAGES') return i.type === 'MESSAGE';
    if (activeFilter === 'ALERTS') return i.type === 'ALERT';
    if (activeFilter === 'APPROVALS') return i.type === 'APPROVAL';
    if (activeFilter === 'ANNOUNCEMENTS') return i.type === 'ANNOUNCEMENT';
    if (activeFilter === 'HISTORY_BOARD') return true;
    return true;
  });

  return (
    <div style={{ padding: '24px', maxWidth: '1400px', margin: '0 auto' }}>
      
      {/* Page Header */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '24px',
        paddingBottom: '16px',
        borderBottom: '1px solid var(--color-rule)'
      }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <div style={{
              width: '38px',
              height: '38px',
              borderRadius: 'var(--radius-sm)',
              background: 'var(--color-accent)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: '#fff'
            }}>
              <ShieldAlert size={22} />
            </div>
            <div>
              <h1 style={{ fontSize: '22px', fontWeight: '800', margin: 0, letterSpacing: '-0.02em' }}>
                Operational Attention & Communication Center
              </h1>
              <p style={{ fontSize: '13px', color: 'var(--color-text-secondary)', margin: '2px 0 0 0' }}>
                Unified Operational Stream • Direct Messages • Team Groups • Broadcasts • System Event Alerts
              </p>
            </div>
          </div>
        </div>

        <div style={{ display: 'flex', gap: '10px' }}>
          <button
            onClick={() => setShowComposer(true)}
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: '8px',
              background: 'var(--color-accent)',
              color: '#fff',
              border: 'none',
              borderRadius: 'var(--radius-xs)',
              padding: '9px 16px',
              fontSize: '13px',
              fontWeight: '700',
              cursor: 'pointer'
            }}
          >
            <Plus size={16} /> New Message / Broadcast
          </button>

          <button
            onClick={() => setExportConsentModal({ datasetName: 'Customer & Financial Stock Ledger' })}
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: '8px',
              background: 'var(--color-canvas)',
              border: '1px solid var(--color-rule)',
              borderRadius: 'var(--radius-xs)',
              padding: '9px 16px',
              fontSize: '13px',
              fontWeight: '600',
              cursor: 'pointer',
              color: 'var(--color-text)'
            }}
          >
            <Download size={16} /> Export Sensitive Ledger
          </button>
        </div>
      </div>

      {/* FILTER CHIPS (ALL, MESSAGES, ALERTS, APPROVALS, ANNOUNCEMENTS, HISTORY BOARD) */}
      <div style={{
        display: 'flex',
        gap: '8px',
        borderBottom: '1px solid var(--color-rule)',
        marginBottom: '24px',
        overflowX: 'auto'
      }}>
        {[
          { id: 'ALL', label: 'ALL EVENTS', icon: Layers },
          { id: 'APPROVALS', label: 'APPROVALS', icon: CheckSquare },
          { id: 'ALERTS', label: 'ALERTS', icon: AlertTriangle },
          { id: 'MESSAGES', label: 'DIRECT & TEAM MESSAGES', icon: MessageSquare },
          { id: 'ANNOUNCEMENTS', label: 'BROADCASTS', icon: Megaphone },
          { id: 'HISTORY_BOARD', label: 'CONVERSATION & TICKET BOARD', icon: Clock }
        ].map(tab => {
          const Icon = tab.icon;
          const isActive = activeFilter === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveFilter(tab.id)}
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: '8px',
                padding: '12px 18px',
                border: 'none',
                borderBottom: isActive ? '2px solid var(--color-accent)' : '2px solid transparent',
                background: 'transparent',
                color: isActive ? 'var(--color-accent)' : 'var(--color-text-secondary)',
                fontWeight: isActive ? '700' : '500',
                fontSize: '13px',
                cursor: 'pointer',
                whiteSpace: 'nowrap'
              }}
            >
              <Icon size={16} color={isActive ? 'var(--color-accent)' : 'currentColor'} />
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>

      {/* OPERATIONAL STREAM */}
      <div style={{ display: 'grid', gap: '16px' }}>
        {filteredItems.map(item => (
          <div
            key={item.id}
            style={{
              background: 'var(--color-paper)',
              border: '1px solid var(--color-rule)',
              borderRadius: 'var(--radius-sm)',
              padding: '20px',
              boxShadow: '0 2px 8px rgba(0,0,0,0.03)'
            }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '12px' }}>
              <div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                  <span style={{ fontSize: '10px', fontFamily: 'monospace', fontWeight: '800', padding: '2px 8px', borderRadius: '4px', background: 'var(--color-canvas)', border: '1px solid var(--color-rule)', color: 'var(--color-accent)' }}>
                    {item.type} • {item.code}
                  </span>
                  <h3 style={{ fontSize: '16px', fontWeight: '700', margin: 0 }}>
                    {item.title}
                  </h3>
                </div>

                <p style={{ fontSize: '13.5px', margin: '8px 0 0 0', color: 'var(--color-text)' }}>
                  {item.summary}
                </p>

                <div style={{ fontSize: '12px', color: 'var(--color-text-secondary)', marginTop: '6px', display: 'flex', gap: '16px', flexWrap: 'wrap' }}>
                  <span>Sender: <strong>{item.sender}</strong></span>
                  {item.recipient && <span>Recipient: <strong>{item.recipient}</strong></span>}
                  {item.relatedRecord && <span>Linked Object: <strong style={{ fontFamily: 'monospace', color: 'var(--color-accent)' }}>{item.relatedRecord}</strong></span>}
                  <span>{new Date(item.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span>
                </div>

                {/* Acknowledgement Progress Bar (For Broadcasts / Team Messages) */}
                {item.requireAck && item.acknowledgements && (
                  <div style={{ marginTop: '12px', padding: '12px', background: 'var(--color-canvas)', border: '1px solid var(--color-rule)', borderRadius: 'var(--radius-xs)' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', fontWeight: '700', marginBottom: '6px' }}>
                      <span>Acknowledgement Progress: {item.acknowledgements.confirmedCount} / {item.acknowledgements.totalRequired} Confirmed</span>
                      <span style={{ color: 'var(--color-accent)' }}>
                        {Math.round((item.acknowledgements.confirmedCount / item.acknowledgements.totalRequired) * 100)}%
                      </span>
                    </div>
                    <div style={{ width: '100%', height: '6px', background: 'var(--color-paper)', borderRadius: '3px', overflow: 'hidden', marginBottom: '8px' }}>
                      <div style={{ width: `${(item.acknowledgements.confirmedCount / item.acknowledgements.totalRequired) * 100}%`, height: '100%', background: 'var(--color-accent)' }} />
                    </div>

                    <div style={{ fontSize: '11px', display: 'flex', gap: '12px', flexWrap: 'wrap', color: 'var(--color-text-secondary)' }}>
                      <span>✓ Confirmed: {item.acknowledgements.confirmedUsers.join(', ')}</span>
                      {item.acknowledgements.pendingUsers.length > 0 && (
                        <span>○ Pending: {item.acknowledgements.pendingUsers.join(', ')}</span>
                      )}
                    </div>
                  </div>
                )}

                {/* Staff Observation Notes */}
                {item.staffNotes && item.staffNotes.length > 0 && (
                  <div style={{ marginTop: '12px', padding: '10px', background: 'var(--color-canvas)', border: '1px solid var(--color-rule)', borderRadius: 'var(--radius-xs)' }}>
                    <div style={{ fontSize: '11px', fontWeight: '700', color: 'var(--color-accent)', marginBottom: '4px' }}>STAFF OBSERVATIONS:</div>
                    {item.staffNotes.map((sn, idx) => (
                      <div key={idx} style={{ fontSize: '12px', color: 'var(--color-text)' }}>
                        <strong>{sn.author} ({sn.time}):</strong> "{sn.note}"
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Action Buttons */}
              <div style={{ display: 'flex', gap: '8px', alignItems: 'center', flexWrap: 'wrap' }}>
                {item.whyExplanation && (
                  <button
                    onClick={() => setSelectedAlertForExplanation(item)}
                    style={{ padding: '7px 12px', background: 'var(--color-canvas)', border: '1px solid var(--color-rule)', borderRadius: 'var(--radius-xs)', fontSize: '12px', cursor: 'pointer' }}
                  >
                    Why Am I Seeing This?
                  </button>
                )}

                {item.requireAck && (
                  <button
                    onClick={() => handleAcknowledge(item)}
                    style={{ padding: '7px 14px', background: 'var(--color-accent)', color: '#fff', border: 'none', borderRadius: 'var(--radius-xs)', fontSize: '12px', fontWeight: '700', cursor: 'pointer' }}
                  >
                    ✓ Acknowledge Receipt
                  </button>
                )}

                <button
                  onClick={() => setStaffNoteModalEntity(item)}
                  style={{ padding: '7px 12px', background: 'var(--color-canvas)', border: '1px solid var(--color-rule)', borderRadius: 'var(--radius-xs)', fontSize: '12px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px' }}
                >
                  <MessageSquare size={14} /> Attach Note
                </button>

                {item.type === 'APPROVAL' && isManager && item.lifecycle !== 'RESOLVED' && (
                  <button
                    onClick={() => setDecisionModalEntity({ item, decision: 'APPROVE' })}
                    style={{ padding: '7px 14px', background: 'var(--color-accent)', color: '#fff', border: 'none', borderRadius: 'var(--radius-xs)', fontSize: '12px', fontWeight: '700', cursor: 'pointer' }}
                  >
                    Review & Authorize
                  </button>
                )}

                {item.type === 'ALERT' && (
                  <button
                    onClick={() => { if (onNavigate) onNavigate('purchases'); }}
                    style={{ padding: '7px 14px', background: 'var(--color-accent)', color: '#fff', border: 'none', borderRadius: 'var(--radius-xs)', fontSize: '12px', fontWeight: '700', cursor: 'pointer' }}
                  >
                    Create Purchase Order
                  </button>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* COMPOSER MODAL (1:1, TEAM, BROADCAST WITH BUSINESS OBJECT LINKING) */}
      {showComposer && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.6)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1100, padding: '20px' }}>
          <div style={{ background: 'var(--color-paper)', border: '1px solid var(--color-rule)', borderRadius: 'var(--radius-sm)', width: '560px', maxWidth: '100%', padding: '24px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px', borderBottom: '1px solid var(--color-rule)', paddingBottom: '12px' }}>
              <h3 style={{ margin: 0, fontSize: '18px', fontWeight: '800' }}>
                New Operational Message / Broadcast
              </h3>
              <button onClick={() => setShowComposer(false)} style={{ background: 'none', border: 'none', cursor: 'pointer' }}>
                <X size={20} />
              </button>
            </div>

            {/* Scope Selection */}
            <div style={{ marginBottom: '16px' }}>
              <label style={{ display: 'block', fontSize: '12px', fontWeight: '700', marginBottom: '6px' }}>COMMUNICATION SCOPE</label>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '8px' }}>
                {[
                  { id: 'INDIVIDUAL', label: 'Individual (1:1)' },
                  { id: 'TEAM', label: 'Team / Group' },
                  { id: 'BROADCAST', label: 'Broadcast (Org-wide)' }
                ].map(s => (
                  <button
                    key={s.id}
                    onClick={() => {
                      if (s.id === 'BROADCAST' && !canBroadcast) {
                        if (onShowToast) onShowToast('warning', 'Permission Restricted', 'Broadcast permission is restricted to Managers and Admins.');
                        return;
                      }
                      setComposerScope(s.id);
                    }}
                    style={{
                      padding: '8px',
                      background: composerScope === s.id ? 'var(--color-accent)' : 'var(--color-canvas)',
                      color: composerScope === s.id ? '#fff' : 'var(--color-text)',
                      border: '1px solid var(--color-rule)',
                      borderRadius: 'var(--radius-xs)',
                      fontSize: '12px',
                      fontWeight: '700',
                      cursor: 'pointer'
                    }}
                  >
                    {s.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Recipient Selection */}
            {composerScope === 'INDIVIDUAL' && (
              <div style={{ marginBottom: '14px' }}>
                <label style={{ display: 'block', fontSize: '12px', fontWeight: '700', marginBottom: '4px' }}>RECIPIENT EMPLOYEE</label>
                <select
                  value={composerRecipient}
                  onChange={e => setComposerRecipient(e.target.value)}
                  style={{ width: '100%', padding: '8px', borderRadius: 'var(--radius-xs)', border: '1px solid var(--color-rule)', background: 'var(--color-canvas)', color: 'var(--color-text)', fontSize: '13px' }}
                >
                  <option value="EMP-00014 (Sales Staff)">John M. (EMP-00014 - Sales Staff)</option>
                  <option value="EMP-00022 (Receiving Operator)">Sarah J. (EMP-00022 - Warehouse)</option>
                  <option value="EMP-00031 (Warehouse Lead)">Peter K. (EMP-00031 - Warehouse Lead)</option>
                </select>
              </div>
            )}

            {composerScope === 'TEAM' && (
              <div style={{ marginBottom: '14px' }}>
                <label style={{ display: 'block', fontSize: '12px', fontWeight: '700', marginBottom: '4px' }}>TARGET OPERATIONAL GROUP</label>
                <select
                  value={composerTeam}
                  onChange={e => setComposerTeam(e.target.value)}
                  style={{ width: '100%', padding: '8px', borderRadius: 'var(--radius-xs)', border: '1px solid var(--color-rule)', background: 'var(--color-canvas)', color: 'var(--color-text)', fontSize: '13px' }}
                >
                  <option value="Warehouse Team">Warehouse Team</option>
                  <option value="Sales Department">Sales Department</option>
                  <option value="Purchasing Team">Purchasing Team</option>
                  <option value="All Managers">All Branch Managers</option>
                </select>
              </div>
            )}

            {/* Subject & Related Business Object Link */}
            <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: '10px', marginBottom: '14px' }}>
              <div>
                <label style={{ display: 'block', fontSize: '12px', fontWeight: '700', marginBottom: '4px' }}>SUBJECT</label>
                <input
                  type="text"
                  value={composerSubject}
                  onChange={e => setComposerSubject(e.target.value)}
                  placeholder="e.g. PO-00431 Receiving Discrepancy"
                  style={{ width: '100%', padding: '8px', borderRadius: 'var(--radius-xs)', border: '1px solid var(--color-rule)', background: 'var(--color-canvas)', color: 'var(--color-text)', fontSize: '13px' }}
                />
              </div>

              <div>
                <label style={{ display: 'block', fontSize: '12px', fontWeight: '700', marginBottom: '4px' }}>LINKED RECORD</label>
                <input
                  type="text"
                  value={composerRelatedRecord}
                  onChange={e => setComposerRelatedRecord(e.target.value)}
                  placeholder="PO-00431"
                  style={{ width: '100%', padding: '8px', borderRadius: 'var(--radius-xs)', border: '1px solid var(--color-rule)', background: 'var(--color-canvas)', color: 'var(--color-text)', fontSize: '13px', fontFamily: 'monospace' }}
                />
              </div>
            </div>

            {/* Message Body */}
            <div style={{ marginBottom: '16px' }}>
              <label style={{ display: 'block', fontSize: '12px', fontWeight: '700', marginBottom: '4px' }}>TRANSACTIONAL INSTRUCTION</label>
              <textarea
                value={composerBody}
                onChange={e => setComposerBody(e.target.value)}
                placeholder="Enter clear operational instruction..."
                rows={4}
                style={{ width: '100%', padding: '10px', borderRadius: 'var(--radius-xs)', border: '1px solid var(--color-rule)', background: 'var(--color-canvas)', color: 'var(--color-text)', fontSize: '13px' }}
              />
            </div>

            {/* Options: Priority & Acknowledgement Checkbox */}
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
              <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '13px', cursor: 'pointer' }}>
                <input
                  type="checkbox"
                  checked={composerRequireAck}
                  onChange={e => setComposerRequireAck(e.target.checked)}
                />
                <strong>Require Formal Acknowledgement</strong>
              </label>

              <select
                value={composerPriority}
                onChange={e => setComposerPriority(e.target.value)}
                style={{ padding: '6px 12px', borderRadius: 'var(--radius-xs)', border: '1px solid var(--color-rule)', background: 'var(--color-canvas)', color: 'var(--color-text)', fontSize: '12px', fontWeight: '700' }}
              >
                <option value="NORMAL">Normal Priority</option>
                <option value="IMPORTANT">Important</option>
                <option value="URGENT">Urgent Action</option>
              </select>
            </div>

            {/* Modal Actions */}
            <div style={{ display: 'flex', gap: '10px', justifyContent: 'flex-end' }}>
              <button onClick={() => setShowComposer(false)} style={{ padding: '9px 16px', background: 'var(--color-canvas)', border: '1px solid var(--color-rule)', borderRadius: 'var(--radius-xs)', cursor: 'pointer' }}>Cancel</button>
              <button onClick={handleSendMessage} style={{ padding: '9px 18px', background: 'var(--color-accent)', color: '#fff', border: 'none', borderRadius: 'var(--radius-xs)', fontWeight: '700', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px' }}>
                <Send size={14} /> Send Transmission
              </button>
            </div>
          </div>
        </div>
      )}

      {/* DECISION MODAL WITH MANDATORY NOTE */}
      {decisionModalEntity && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.6)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1100, padding: '20px' }}>
          <div style={{ background: 'var(--color-paper)', border: '1px solid var(--color-rule)', borderRadius: 'var(--radius-sm)', width: '500px', maxWidth: '100%', padding: '24px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
              <h3 style={{ margin: 0, fontSize: '18px', fontWeight: '800' }}>
                Manager Decision: {decisionModalEntity.decision}
              </h3>
              <button onClick={() => setDecisionModalEntity(null)} style={{ background: 'none', border: 'none', cursor: 'pointer' }}>
                <X size={20} />
              </button>
            </div>

            <div style={{ fontSize: '13px', marginBottom: '14px' }}>
              Target Item: <strong>{decisionModalEntity.item.code}</strong> — {decisionModalEntity.item.title}
            </div>

            <div style={{ marginBottom: '20px' }}>
              <label style={{ display: 'block', fontSize: '13px', fontWeight: '700', marginBottom: '6px' }}>
                Mandatory Manager Decision Note / Audit Justification:
              </label>
              <textarea
                value={decisionNote}
                onChange={e => setDecisionNote(e.target.value)}
                placeholder="Enter mandatory justification note for audit ledger..."
                rows={4}
                style={{ width: '100%', padding: '10px', borderRadius: 'var(--radius-xs)', border: '1px solid var(--color-rule)', background: 'var(--color-canvas)', color: 'var(--color-text)', fontSize: '13px' }}
              />
            </div>

            <div style={{ display: 'flex', gap: '10px', justifyContent: 'flex-end' }}>
              <button onClick={() => setDecisionModalEntity(null)} style={{ padding: '9px 16px', background: 'var(--color-canvas)', border: '1px solid var(--color-rule)', borderRadius: 'var(--radius-xs)', cursor: 'pointer' }}>Cancel</button>
              <button onClick={handleExecuteManagerDecision} style={{ padding: '9px 18px', background: 'var(--color-accent)', color: '#fff', border: 'none', borderRadius: 'var(--radius-xs)', fontWeight: '700', cursor: 'pointer' }}>
                Confirm & Log Decision
              </button>
            </div>
          </div>
        </div>
      )}

      {/* STAFF OBSERVATION NOTE MODAL */}
      {staffNoteModalEntity && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.6)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1100, padding: '20px' }}>
          <div style={{ background: 'var(--color-paper)', border: '1px solid var(--color-rule)', borderRadius: 'var(--radius-sm)', width: '480px', maxWidth: '100%', padding: '24px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
              <h3 style={{ margin: 0, fontSize: '18px', fontWeight: '800' }}>
                Attach Staff Observation Note
              </h3>
              <button onClick={() => setStaffNoteModalEntity(null)} style={{ background: 'none', border: 'none', cursor: 'pointer' }}>
                <X size={20} />
              </button>
            </div>

            <div style={{ fontSize: '13px', marginBottom: '14px' }}>
              Target Item: <strong>{staffNoteModalEntity.code}</strong>
            </div>

            <div style={{ marginBottom: '20px' }}>
              <textarea
                value={staffObservationNote}
                onChange={e => setStaffObservationNote(e.target.value)}
                placeholder="e.g. Supplier driver confirmed 4 units backordered on delivery slip."
                rows={3}
                style={{ width: '100%', padding: '10px', borderRadius: 'var(--radius-xs)', border: '1px solid var(--color-rule)', background: 'var(--color-canvas)', color: 'var(--color-text)', fontSize: '13px' }}
              />
            </div>

            <div style={{ display: 'flex', gap: '10px', justifyContent: 'flex-end' }}>
              <button onClick={() => setStaffNoteModalEntity(null)} style={{ padding: '9px 16px', background: 'var(--color-canvas)', border: '1px solid var(--color-rule)', borderRadius: 'var(--radius-xs)', cursor: 'pointer' }}>Cancel</button>
              <button onClick={handleAddStaffNote} style={{ padding: '9px 18px', background: 'var(--color-accent)', color: '#fff', border: 'none', borderRadius: 'var(--radius-xs)', fontWeight: '700', cursor: 'pointer' }}>Attach Note</button>
            </div>
          </div>
        </div>
      )}

      {/* SENSITIVE DATA EXPORT CONSENT MODAL */}
      {exportConsentModal && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.6)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1100, padding: '20px' }}>
          <div style={{ background: 'var(--color-paper)', border: '1px solid var(--color-rule)', borderRadius: 'var(--radius-sm)', width: '520px', maxWidth: '100%', padding: '24px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <Lock size={22} style={{ color: 'var(--color-accent)' }} />
                <h3 style={{ margin: 0, fontSize: '18px', fontWeight: '800' }}>
                  Sensitive Data Export Consent Required
                </h3>
              </div>
              <button onClick={() => setExportConsentModal(null)} style={{ background: 'none', border: 'none', cursor: 'pointer' }}>
                <X size={20} />
              </button>
            </div>

            <div style={{ background: 'var(--color-canvas)', border: '1px solid var(--color-rule)', borderRadius: 'var(--radius-xs)', padding: '12px', fontSize: '12.5px', marginBottom: '16px' }}>
              ⚠️ You are attempting to export sensitive dataset: <strong>{exportConsentModal.datasetName}</strong>. Every export is permanently logged into the security compliance audit trail.
            </div>

            <div style={{ marginBottom: '20px' }}>
              <label style={{ display: 'block', fontSize: '13px', fontWeight: '700', marginBottom: '6px' }}>
                Export Reason / Business Justification:
              </label>
              <textarea
                value={exportReason}
                onChange={e => setExportReason(e.target.value)}
                placeholder="e.g. Monthly external financial audit compliance export for Q3."
                rows={3}
                style={{ width: '100%', padding: '10px', borderRadius: 'var(--radius-xs)', border: '1px solid var(--color-rule)', background: 'var(--color-canvas)', color: 'var(--color-text)', fontSize: '13px' }}
              />
            </div>

            <div style={{ display: 'flex', gap: '10px', justifyContent: 'flex-end' }}>
              <button onClick={() => setExportConsentModal(null)} style={{ padding: '9px 16px', background: 'var(--color-canvas)', border: '1px solid var(--color-rule)', borderRadius: 'var(--radius-xs)', cursor: 'pointer' }}>Cancel</button>
              <button onClick={handleConfirmExport} style={{ padding: '9px 18px', background: 'var(--color-accent)', color: '#fff', border: 'none', borderRadius: 'var(--radius-xs)', fontWeight: '700', cursor: 'pointer' }}>
                Authorize Export & Log
              </button>
            </div>
          </div>
        </div>
      )}

      {/* WHY EXPLANATION MODAL */}
      {selectedAlertForExplanation && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.6)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1100, padding: '20px' }}>
          <div style={{ background: 'var(--color-paper)', border: '1px solid var(--color-rule)', borderRadius: 'var(--radius-sm)', width: '580px', maxWidth: '100%', padding: '24px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px', borderBottom: '1px solid var(--color-rule)', paddingBottom: '12px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <HelpCircle size={22} color="var(--color-accent)" />
                <h3 style={{ margin: 0, fontSize: '18px', fontWeight: '800' }}>
                  Why Am I Seeing This?
                </h3>
              </div>
              <button onClick={() => setSelectedAlertForExplanation(null)} style={{ background: 'none', border: 'none', cursor: 'pointer' }}>
                <X size={20} />
              </button>
            </div>

            <div style={{ fontSize: '13px', lineHeight: 1.6 }}>
              <div><strong>Trigger Rule:</strong> {selectedAlertForExplanation.whyExplanation.trigger}</div>
              <div style={{ marginTop: '8px', fontFamily: 'monospace', background: 'var(--color-canvas)', padding: '10px', border: '1px solid var(--color-rule)', borderRadius: 'var(--radius-xs)' }}>
                {selectedAlertForExplanation.whyExplanation.formula}
              </div>
              <div style={{ marginTop: '12px', fontSize: '12px', color: 'var(--color-text-secondary)' }}>
                Audit Reference: {selectedAlertForExplanation.whyExplanation.auditRef}
              </div>
            </div>

            <div style={{ marginTop: '20px', display: 'flex', justifyContent: 'flex-end' }}>
              <button onClick={() => setSelectedAlertForExplanation(null)} style={{ padding: '9px 18px', background: 'var(--color-accent)', color: '#fff', border: 'none', borderRadius: 'var(--radius-xs)', fontWeight: '600', cursor: 'pointer' }}>
                Close Explanation
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
